### ISSUE TITLE
Can't get it going

### ISSUE THREAD

**Issue by jonnyijapan** [jasperblues/XcodeEditor#42]
I added this frameowrk to a OS X cmd line tool project, but I get this when running my app. It seems as the framework is not included in my binary:

dyld: Library not loaded: @executable_path/../Frameworks/XcodeEditor.framework/Versions/A/XcodeEditor
  Referenced from: /Users/jonny/Library/Developer/Xcode/DerivedData/fixunityoutput-gaczjmlpbieybbcwzokbxsrzfzwj/Build/Products/Debug/fixunityoutput
  Reason: image not found

**Comment by jasperblues** [comment]
Can you try using CocoaPods or just paste source files into your project?
