### ISSUE TITLE
Rename `XCBuildConfiguration` to something else

### ISSUE THREAD

**Issue by johnboiles** [jasperblues/XcodeEditor#44]
Because this class's naming conflicts with Xcode's internal `XCBuildConfiguration` you get scary warnings when using plugins that rely on XcodeEditor. The warnings look like this:

    objc[30712]: Class XCBuildConfiguration is implemented in both /Applications/Xcode6.1.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Users/seandawson/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.

Some related issues:
https://github.com/markohlebar/Peckham/issues/27
https://github.com/lucholaf/Auto-Importer-for-Xcode/issues/10

**Comment by jasperblues** [comment]
Oops. In retrospect perhaps `XC` was not the best choice of prefix. Renaming that enum.

**Comment by jasperblues** [comment]
er, renaming that class, I mean.

**Comment by jasperblues** [comment]
Pushed. Also fixed broken tests (except for one) due to the Script Build phase to extract test assets to /tmp having gone missing. (due to XC upgrade?)

**Comment by jasperblues** [comment]
Need a new pod version?

**Comment by johnboiles** [comment]
A new pod version would be great. Thanks @jasperblues!!

**Comment by jasperblues** [comment]
OK pushed v1.6.2 (previous version was 1.6 - suddenly we have semantic versioning). I had to spend some time fixing some warnings (crusty old code) to get it to pass podspec linting.

**Comment by johnboiles** [comment]
Woohoo thanks!
